# convert an encoded message
$profile="shared-admin"
$encoded_message="QNiZEflRPwm4QxSvhIk5Li8KR2s0h0WpCAEEUWMEHCspXX_JtlYUvMDRW5WIKroPnGMcB9ySqCHubbqmM-fH1fDcj4DqQZgotRotr4J9q0uPZkLByk2eUbNlF0v8OVh5zrJ-yVSxK8oD-ag57zJOEeBpfp2AAHX7ky2kFiak1fxNYKr-ztEdPuKyq0TXoS_tMdKK5XffqE-0-A7oBTKBmu6LvVfmOBrjC--inGpGO9GoW3noKWIpqnyGJLBx6jTdbVnsSLIc1cFhwoSQ7sWIwaqnEjFZiADYXNMTLekacZRPTPlGd7PTqyuYxG94b7zJFsqUggholK4ejj0lVILMaLXPgM4P2P9ZaQVculjazA87xS3vVSclyaJ-p70fEs3-n9Wx-kSolIgHhAR8m0wQVGPNRl6jqD_u9qAW6AhfrYrAVwHBegChBCyZFcP13fY_Z3MUrMnevzfA03NOI0IytqzNGUCIydipHoOUJ-SfKLzVmw0Q11Ct5KZyUez1Fkw7NgqTxY490aatxcOKAW7CLOG6NYUb6LftoYlgBUyCfUoag6bpQYuem16JrT8OHpgrBjRvchnFXraD-XfHXsRh7u49GWif3AIjN8FnGoQ-PPmimqXQfiH4VB42RkbDoQXZZyRdAi9b38LDoQadkyfT35ZuYdKhcE0r-4r0gEhxFRQwLcZtceQGQEskOpSHt8sJr-s0LEzCflDewaaFSJyb7IkLXBk94193dDDYG8tsi7D68E4gPshD4qGYcRtmDknUcZ3_oH5h2O-suR8qbOuA6_jqLz2dehCFxwuOSTEBD_3hcKcYjcRfMqyUJPMP8RT8BDQF6MBnp1ykLqM7Kvg"


$decoded_message=Convert-STSAuthorizationMessage -EncodedMessage $encoded_message -Region us-west-2 -ProfileName $profile #-credential $creds
Write-Output $decoded_message

# convert using CLI
#aws sts decode-authorization-message --encoded-message $encoded_message --region us-west-2